codecov:
  disable_default_path_fixes: true
  require_ci_to_pass: false
comment:
  after_n_builds: 7
flags:
  Bicomplexes:
    paths:
      - "Bicomplexes/"
  ComplexesCategories:
    paths:
      - "ComplexesCategories/"
  DerivedCategories:
    paths:
      - "DerivedCategories/"
  HomotopyCategories:
    paths:
      - "HomotopyCategories/"
  StableCategories:
    paths:
      - "StableCategories/"
  ToolsForHigherHomologicalAlgebra:
    paths:
      - "ToolsForHigherHomologicalAlgebra/"
  TriangulatedCategories:
    paths:
      - "TriangulatedCategories/"
